// Generated by apps/og/scripts/gen-plate.ts — do not hand-edit; re-run `pnpm gen-plate` to regenerate.
//
// Union of the Unicode code points covered by the 15 card fonts (fonts/*.woff), built from their
// cmaps with fontkit (docs/og-plan.md O19, §2.2). A card field whose sanitised text has a character
// outside this set is left off the image (text.ts's `fieldForImage`/`initialsFor`).
//
// Stored as sorted, inclusive [start, end] code point ranges: the 15 fonts share only a few hundred
// code points between them, so this is far smaller than 15 per-font glyph lists, and a binary search
// over it is plenty fast for a handful of short fields per render.

const COVERED_RANGES: readonly [number, number][] = [
  [0, 0],
  [13, 13],
  [32, 126],
  [160, 172],
  [174, 328],
  [330, 382],
  [399, 399],
  [402, 402],
  [416, 417],
  [431, 432],
  [452, 460],
  [486, 487],
  [490, 491],
  [506, 539],
  [554, 557],
  [560, 563],
  [567, 567],
  [601, 601],
  [710, 711],
  [730, 730],
  [732, 733],
  [768, 769],
  [771, 772],
  [776, 777],
  [803, 803],
  [880, 887],
  [890, 895],
  [900, 906],
  [908, 908],
  [910, 929],
  [931, 993],
  [1008, 1119],
  [1168, 1169],
  [1200, 1201],
  [7688, 7689],
  [7692, 7695],
  [7700, 7703],
  [7708, 7709],
  [7712, 7713],
  [7716, 7717],
  [7722, 7723],
  [7726, 7727],
  [7734, 7735],
  [7738, 7739],
  [7746, 7753],
  [7756, 7763],
  [7770, 7771],
  [7774, 7785],
  [7788, 7791],
  [7800, 7803],
  [7808, 7813],
  [7822, 7823],
  [7826, 7827],
  [7831, 7831],
  [7838, 7838],
  [7840, 7929],
  [8194, 8194],
  [8201, 8201],
  [8203, 8203],
  [8211, 8212],
  [8216, 8218],
  [8220, 8222],
  [8224, 8224],
  [8226, 8226],
  [8230, 8230],
  [8242, 8243],
  [8249, 8250],
  [8260, 8260],
  [8353, 8353],
  [8355, 8356],
  [8358, 8366],
  [8369, 8373],
  [8376, 8378],
  [8380, 8383],
  [8467, 8467],
  [8470, 8470],
  [8482, 8482],
  [8593, 8593],
  [8595, 8595],
  [8722, 8722],
  [8725, 8725],
  [65535, 65535],
];

function isCoveredCodePoint(codePoint: number): boolean {
  let lo = 0;
  let hi = COVERED_RANGES.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    const range = COVERED_RANGES[mid];
    if (!range) break;
    const [start, end] = range;
    if (codePoint < start) hi = mid - 1;
    else if (codePoint > end) lo = mid + 1;
    else return true;
  }
  return false;
}

/** True when every code point in `text` is drawable with the card's fonts. Empty string is trivially covered. */
export function isFullyCovered(text: string): boolean {
  for (const ch of text) {
    if (!isCoveredCodePoint(ch.codePointAt(0)!)) return false;
  }
  return true;
}
