// Regenerates src/render/icon-paths.ts from the ionicons SVG sources (devDependency `ionicons`), for
// every icon name the signed-out mobile components can render. icon-paths.ts is committed, so
// `pnpm build` never needs ionicons installed and the deployed Function has no dependency on it.
//
// Run after adding a new icon to one of the source files below:
//   pnpm --filter @chatsoon/web run gen-icons
//
// Per docs/public-pages-plan.md §4 WP-B2: "reads ionicons/dist/svg/<name>.svg ... for the names used
// by the public components (grep components/web, components/booking and components/moderation)."
// That grep was done by hand once, because the real usages aren't all literal `name="…"` props — some
// are built from a lookup object (contact-pills.tsx's CHANNEL_ICON), a plain function's return value
// (booking-links-card.tsx's providerIcon) or a JSON content file the components render
// (content/landing.json's per-feature `icon` field) — so a single regex would both over- and
// under-match. PUBLIC_ICON_NAMES below is that curated result; SOURCE_FILES is scanned only to warn
// when a new ionicon-shaped literal shows up that isn't in the list yet, as a drift check, not as the
// source of truth.

import { createRequire } from 'node:module';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const mobileComponents = path.resolve(root, '../mobile/src/components');

const SOURCE_DIRS = ['web', 'booking', 'moderation'].map((d) => path.join(mobileComponents, d));

// Every icon rendered by apps/mobile/src/components/{web,booking,moderation}, including the ones
// content/landing.json supplies to landing.tsx's feature cards. Keep this alphabetised; add a name
// the moment a component starts using it.
const PUBLIC_ICON_NAMES = [
  'alert-circle-outline',
  'briefcase-outline',
  'calendar-outline',
  'call-outline',
  'chatbubble-ellipses-outline',
  'checkmark-circle',
  'chevron-forward',
  'close',
  'download-outline',
  'flag-outline',
  'globe-outline',
  'lock-closed-outline',
  'logo-discord',
  'logo-google',
  'logo-linkedin',
  'logo-microsoft',
  'logo-whatsapp',
  'logo-x',
  'logo-youtube',
  'open-outline',
  'paper-plane-outline',
  'phone-portrait-outline',
  'pricetags-outline',
  'qr-code-outline',
  'radio-button-off',
  'radio-button-on',
  'ribbon-outline',
  'scan-outline',
  'search-outline',
  'send-outline',
  'sparkles',
  'sparkles-outline',
] as const;

function listFiles(dir: string, exts: string[]): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return listFiles(full, exts);
    return exts.includes(path.extname(entry.name)) ? [full] : [];
  });
}

/** Loose enough to catch most ionicon-shaped string literals; only used for the drift warning. */
const ICON_SHAPED = /^(?:logo|md|ios)-[a-z0-9-]+$|^[a-z][a-z0-9]*(?:-[a-z0-9]+)*-(?:outline|sharp)$|^[a-z][a-z0-9]*$/;
const NOT_ICONS = new Set(['name', 'icon', 'description', 'robots', 'website', 'form']);

function warnAboutDrift(): void {
  const found = new Set<string>();
  for (const file of SOURCE_DIRS.flatMap((d) => listFiles(d, ['.ts', '.tsx']))) {
    const src = readFileSync(file, 'utf8');
    for (const m of src.matchAll(/['"]([a-z][a-z0-9-]+)['"]/g)) {
      const candidate = m[1];
      if (candidate && ICON_SHAPED.test(candidate) && !NOT_ICONS.has(candidate)) found.add(candidate);
    }
  }
  const missing = [...found].filter((n) => !(PUBLIC_ICON_NAMES as readonly string[]).includes(n) && iconFileExists(n));
  if (missing.length) {
    console.warn(
      `gen-icons: found ionicon-shaped name(s) not in PUBLIC_ICON_NAMES, add them if they're really icons: ${missing.join(', ')}`,
    );
  }
}

function iconFileExists(name: string): boolean {
  try {
    require.resolve(`ionicons/dist/svg/${name}.svg`);
    return true;
  } catch {
    return false;
  }
}

function readIcon(name: string): { viewBox: string; body: string } {
  const file = require.resolve(`ionicons/dist/svg/${name}.svg`);
  const svg = readFileSync(file, 'utf8');
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  const body = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/)?.[1]?.trim();
  if (!viewBox || !body) throw new Error(`gen-icons: could not parse ${file}`);
  return { viewBox, body };
}

warnAboutDrift();

const entries = PUBLIC_ICON_NAMES.map((name) => [name, readIcon(name)] as const);

const out = `// Generated by scripts/gen-icons.ts from ionicons@${(require('ionicons/package.json') as { version: string }).version} — do not edit by hand.
// Source names: PUBLIC_ICON_NAMES in scripts/gen-icons.ts (apps/mobile/src/components/{web,booking,moderation}).

export interface IconPath {
  viewBox: string;
  body: string;
}

export const ICON_PATHS = {
${entries.map(([name, p]) => `  '${name}': { viewBox: ${JSON.stringify(p.viewBox)}, body: ${JSON.stringify(p.body)} },`).join('\n')}
} as const satisfies Record<string, IconPath>;

export type IconName = keyof typeof ICON_PATHS;
`;

const outFile = path.join(root, 'src/render/icon-paths.ts');
writeFileSync(outFile, out);
console.log(`gen-icons: wrote ${entries.length} icons to ${path.relative(root, outFile)}`);
