// Generated by apps/og/scripts/gen-generic.ts — do not hand-edit; re-run the script to regenerate.
export const DEFAULT_OG_IMAGE = {
  path: '/og/chatsoon-5a6e4ad4.jpg',
  width: 1200,
  height: 630,
  type: 'image/jpeg',
  alt: 'Chatsoon: Meet people. Follow up. The networking CRM for events.',
} as const;
