// Follow-ups (issue #33, PR A): the due-date rule, channels and message template shared by the
// Worker and the app. Pure string/date helpers only - no zod (schemas.ts), no URL/DOM APIs, so this
// module stays safe for a direct import (see links.ts, referrals.ts).

import { toLinkUrl } from './links';

/** contacts.follow_up_channel. 'copy' covers Telegram, LinkedIn and X, which have no prefill support:
 * the message is copied to the clipboard and the chat or profile is opened separately. */
export const FOLLOW_UP_CHANNELS = ['whatsapp', 'sms', 'email', 'telegram', 'linkedin', 'x', 'copy'] as const;
export type FollowUpChannel = (typeof FOLLOW_UP_CHANNELS)[number];

/** "Followed up on 3 Oct via <label>". */
export const FOLLOW_UP_CHANNEL_LABELS: Record<FollowUpChannel, string> = {
  whatsapp: 'WhatsApp',
  sms: 'text message',
  email: 'email',
  telegram: 'Telegram',
  linkedin: 'LinkedIn',
  x: 'X',
  copy: 'a copied message',
};

const DAY_MS = 24 * 60 * 60 * 1000;

/**
 * "Remind me again" options offered after following up (PATCH /contacts/:id/follow-up):
 * `remindInDays`, or null for "Never".
 */
export const REMIND_DAY_OPTIONS = [3, 7, 14] as const;
export type RemindDays = (typeof REMIND_DAY_OPTIONS)[number];

export const REMIND_OPTION_LABELS: Record<RemindDays, string> = {
  3: '3 days',
  7: '1 week',
  14: '2 weeks',
};

/** `follow_up_due_at` for a "Remind me again" choice: `days` from `from`, or null for "Never". */
export function remindDueAt(days: RemindDays | null, from: Date): Date | null {
  return days === null ? null : new Date(from.getTime() + days * DAY_MS);
}

/**
 * `contacts.follow_up_due_at` for a newly created contact, from its priority and `created_at`
 * (issue #33): priority 5 or 4 is due immediately; 3, or no priority, is due the next day;
 * 2 or 1 is due in two days. Pure and covers every creation path (manual, QR scan, card photo,
 * app connections, web_connect) and a later priority change while not yet followed up.
 */
export function followUpDueAt(priority: number | null | undefined, createdAt: Date): Date {
  if (priority === 5 || priority === 4) return new Date(createdAt.getTime());
  if (priority === 2 || priority === 1) return new Date(createdAt.getTime() + 2 * DAY_MS);
  return new Date(createdAt.getTime() + DAY_MS);
}

/** True when a contact is due for a follow-up right now: a due date is set and it has passed,
 * whether that's a brand new contact or one due again after a "Remind me again". */
export function isFollowUpDue(contact: { followUpDueAt: string | null }, now: Date = new Date()): boolean {
  return contact.followUpDueAt !== null && new Date(contact.followUpDueAt).getTime() <= now.getTime();
}

// ---------------------------------------------------------------------------
// Draft message (PR A: a fixed template; PR B swaps `followUpTemplateBody` for an AI-generated body
// and calls `composeFollowUpMessage` with it - the signature and its composition never change).
// ---------------------------------------------------------------------------

/** The first word of a contact's name, for greeting them by first name - "Marcus Chen" to "Marcus". */
export function followUpFirstName(name: string): string {
  return name.trim().split(/\s+/)[0] || name;
}

/** The editable part of the draft: "Hi Marcus, great to meet you at Token2049! Let's keep in touch." */
export function followUpTemplateBody(firstName: string, eventName: string | null | undefined): string {
  const where = eventName ? ` at ${eventName}` : '';
  return `Hi ${firstName}, great to meet you${where}! Let's keep in touch.`;
}

/** Always appended after the editable body, never generated by it (PR B still only replaces the body). */
export function followUpSignature(displayName: string, referralLink: string): string {
  return `Chat soon,\n${displayName}\n\nGet your own Chatsoon profile: ${referralLink}`;
}

/** The full draft text: the (template or AI) body, a blank line, then the fixed signature. */
export function composeFollowUpMessage(body: string, signature: string): string {
  return `${body}\n\n${signature}`;
}

// ---------------------------------------------------------------------------
// Send targets. Each reuses toLinkUrl's phone/email parsing (links.ts) rather than re-validating -
// a contact's phone/email are free text (packages/shared/src/schemas.ts contactFields), not
// pre-normalised the way a profile's own contact fields are (profile-contact.ts).
// ---------------------------------------------------------------------------

const FOLLOW_UP_EMAIL_SUBJECT = 'Great to meet you';

/** Whether `contact` has data this channel's button needs (issue #33: only shown channels a contact
 * has data for). 'copy' always has something to copy. */
export function followUpChannelAvailable(
  channel: FollowUpChannel,
  contact: {
    phone: string | null;
    email: string | null;
    telegram: string | null;
    linkedinUrl: string | null;
    xHandle: string | null;
  },
): boolean {
  switch (channel) {
    case 'whatsapp':
    case 'sms':
      return toLinkUrl('phone', contact.phone) !== null;
    case 'email':
      return toLinkUrl('email', contact.email) !== null;
    case 'telegram':
      return toLinkUrl('telegram', contact.telegram) !== null;
    case 'linkedin':
      return toLinkUrl('linkedin', contact.linkedinUrl) !== null;
    case 'x':
      return toLinkUrl('x', contact.xHandle) !== null;
    case 'copy':
      return true;
  }
}

/** `https://wa.me/<digits>?text=<encoded>`, or null when `phone` isn't a usable number. */
export function followUpWhatsAppUrl(phone: string | null | undefined, message: string): string | null {
  const tel = toLinkUrl('phone', phone);
  if (!tel) return null;
  return `https://wa.me/${tel.replace(/^tel:\+?/, '')}?text=${encodeURIComponent(message)}`;
}

/**
 * `sms:<phone>?&body=<encoded>` for a mobile browser (native uses expo-sms's sendSMSAsync instead,
 * which needs no URL). The `?&` separator - neither a bare `?` nor `&` - is the one both iOS and
 * Android's SMS apps accept.
 */
export function followUpSmsWebUrl(phone: string | null | undefined, message: string): string | null {
  const tel = toLinkUrl('phone', phone);
  if (!tel) return null;
  return `sms:${tel.replace(/^tel:/, '')}?&body=${encodeURIComponent(message)}`;
}

/** `mailto:<email>?subject=Great to meet you&body=<encoded>`, or null when `email` isn't usable. */
export function followUpMailtoUrl(email: string | null | undefined, message: string): string | null {
  const mailto = toLinkUrl('email', email);
  if (!mailto) return null;
  return `${mailto}?subject=${encodeURIComponent(FOLLOW_UP_EMAIL_SUBJECT)}&body=${encodeURIComponent(message)}`;
}
