// Generates the generic Open Graph image (docs/og-plan.md §2.1, WP-1): crops Peter's X header art,
// resizes to the OG canvas and encodes as a mozjpeg progressive JPEG. The file name carries a hash of
// the encoded bytes (O5), so og-asset.ts and the static file always agree on which image exists and
// old copies never linger under a stale name.
//
// Uses the hoisted root `sharp` (node-linker=hoisted) — apps/og has no package.json and nothing is
// installed for this script. Run from the repo root:
//   npx tsx apps/og/scripts/gen-generic.ts

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import sharp from 'sharp';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const SOURCE = path.join(ROOT, 'apps/og/assets/brand/x-header-2172x724.png');
const OUT_DIR = path.join(ROOT, 'apps/mobile/public/og');
const OG_ASSET_TS = path.join(ROOT, 'apps/web/src/render/og-asset.ts');

const WIDTH = 1200;
const HEIGHT = 630;
const MAX_BYTES = 300 * 1024; // §2.1: "fails if the output isn't 1200×630 or is 300 KB or larger"
const ALT = 'Chatsoon: Meet people. Follow up. The networking CRM for events.';

async function main(): Promise<void> {
  // O3: crop at x=356 (1379×724) — clears the right-edge card slivers and leaves the bubble ~95px
  // of margin, beats the centre crop at x=397 which cuts into the tags lens.
  const buffer = await sharp(SOURCE)
    .extract({ left: 356, top: 0, width: 1379, height: 724 })
    .resize(WIDTH, HEIGHT, { kernel: 'lanczos3' })
    .jpeg({ quality: 85, mozjpeg: true, progressive: true }) // O4: JPEG only; sRGB, metadata stripped
    .toBuffer();

  if (buffer[0] !== 0xff || buffer[1] !== 0xd8) {
    throw new Error('gen-generic: output has no JPEG SOI marker');
  }
  const meta = await sharp(buffer).metadata();
  if (meta.width !== WIDTH || meta.height !== HEIGHT) {
    throw new Error(`gen-generic: output is ${meta.width}x${meta.height}, expected ${WIDTH}x${HEIGHT}`);
  }
  if (buffer.length >= MAX_BYTES) {
    throw new Error(`gen-generic: output is ${buffer.length} bytes, must be under ${MAX_BYTES}`);
  }

  const sha8 = createHash('sha256').update(buffer).digest('hex').slice(0, 8);
  const filename = `chatsoon-${sha8}.jpg`;
  const outPath = path.join(OUT_DIR, filename);

  // The hash is over the encoded bytes, so a rerun with the same source and sharp version must land
  // on the same name with the same content — that's the "byte-identical on a second run" check.
  if (existsSync(outPath)) {
    const existing = readFileSync(outPath);
    if (!existing.equals(buffer)) {
      throw new Error(`gen-generic: ${filename} already exists with different bytes than this run produced`);
    }
  }

  mkdirSync(OUT_DIR, { recursive: true });
  // O5: the name carries the hash, so any older chatsoon-*.jpg is stale and gets removed.
  for (const entry of readdirSync(OUT_DIR)) {
    if (/^chatsoon-[0-9a-f]{8}\.jpg$/.test(entry) && entry !== filename) {
      rmSync(path.join(OUT_DIR, entry));
      console.log(`gen-generic: removed stale ${entry}`);
    }
  }
  writeFileSync(outPath, buffer);

  const assetSource = `// Generated by apps/og/scripts/gen-generic.ts — do not hand-edit; re-run the script to regenerate.
export const DEFAULT_OG_IMAGE = {
  path: '/og/${filename}',
  width: ${WIDTH},
  height: ${HEIGHT},
  type: 'image/jpeg',
  alt: '${ALT}',
} as const;
`;
  writeFileSync(OG_ASSET_TS, assetSource);

  console.log(`gen-generic: wrote ${path.relative(ROOT, outPath)} (${buffer.length} bytes, sha8 ${sha8})`);
  console.log(`gen-generic: wrote ${path.relative(ROOT, OG_ASSET_TS)}`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
